// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUl5YsrgRLZn7nqnvKstwB6-PwsKOu3D8',
    appId: '1:491479929136:web:7853030fcc82b20ebcf8f5',
    messagingSenderId: '491479929136',
    projectId: 'shopsbank-405b5',
    authDomain: 'shopsbank-405b5.firebaseapp.com',
    storageBucket: 'shopsbank-405b5.appspot.com',
    measurementId: 'G-REB1P0PTEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1oiumMw27H-c4dKCpk71ACiBZuhCC-xc',
    appId: '1:491479929136:android:8f9ce1098a9c2c15bcf8f5',
    messagingSenderId: '491479929136',
    projectId: 'shopsbank-405b5',
    storageBucket: 'shopsbank-405b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaqt8ooRS0vO5A2ESqPKvWfRNHGWkpmkY',
    appId: '1:491479929136:ios:370c743faa1d997abcf8f5',
    messagingSenderId: '491479929136',
    projectId: 'shopsbank-405b5',
    storageBucket: 'shopsbank-405b5.appspot.com',
    iosBundleId: 'com.example.anwerShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaqt8ooRS0vO5A2ESqPKvWfRNHGWkpmkY',
    appId: '1:491479929136:ios:370c743faa1d997abcf8f5',
    messagingSenderId: '491479929136',
    projectId: 'shopsbank-405b5',
    storageBucket: 'shopsbank-405b5.appspot.com',
    iosBundleId: 'com.example.anwerShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUl5YsrgRLZn7nqnvKstwB6-PwsKOu3D8',
    appId: '1:491479929136:web:5a325c9779a489c7bcf8f5',
    messagingSenderId: '491479929136',
    projectId: 'shopsbank-405b5',
    authDomain: 'shopsbank-405b5.firebaseapp.com',
    storageBucket: 'shopsbank-405b5.appspot.com',
    measurementId: 'G-0TQ4Y09J47',
  );
}
